Repository cellarium-ai/cellarium-ml, pull requests merged in 2023-08, with the labels that each got.

#62 Embedding Writer
  scvid/callbacks/__init__.py
  scvid/callbacks/prediction_writer.py
  scvid/data/dadc_datamodule.py
  scvid/data/dadc_dataset.py
  scvid/data/distributed_anndata.py
  scvid/data/util.py
  scvid/module/__init__.py
  scvid/module/base_module.py
  scvid/module/incremental_pca.py
  scvid/module/onepass_mean_var_std.py
  scvid/module/probabilistic_pca.py
  scvid/train/training_plan.py
  test/test_dataset.py
  test/test_distributed_anndata.py
  test/test_examples.py
Labels: awaiting review

#68 Note about how to prevent OOM error during predict run
  scvid/callbacks/prediction_writer.py
Labels: documentation, awaiting review, easy

#63 DistributedPCA
  scvid/callbacks/module_checkpoint.py
  scvid/module/incremental_pca.py
  scvid/train/training_plan.py
  test/test_ipca.py
Labels: enhancement, awaiting review

#69 Allow to validate only a subset of `AnnData.obs` columns
  scvid/data/distributed_anndata.py
  scvid/data/schema.py
  test/test_schema.py
Labels: enhancement, awaiting review

#65 `TDigest` module to calculate non-zero median
  .github/workflows/ci.yml
  examples/tdigest.py
  scvid/callbacks/module_checkpoint.py
  scvid/module/__init__.py
  scvid/module/from_cli.py
  scvid/module/tdigest.py
  scvid/transforms/__init__.py
  scvid/transforms/transforms.py
  setup.py
  test/test_examples.py
  test/test_tdigest.py
Labels: enhancement, awaiting review

#70 `pyproject.toml`
  MANIFEST.in
  Makefile
  examples/incremental_pca.py
  examples/onepass_mean_var_std.py
  examples/probabilistic_pca.py
  examples/tdigest.py
  pyproject.toml
  scripts/update_headers.py
  scvid/__init__.py
  scvid/_version.py
  scvid/callbacks/module_checkpoint.py
  scvid/callbacks/prediction_writer.py
  scvid/callbacks/variance_monitor.py
  scvid/data/dadc_dataset.py
  scvid/data/distributed_anndata.py
  scvid/data/sampler.py
  scvid/data/util.py
  scvid/module/base_module.py
  scvid/module/from_cli.py
  scvid/module/incremental_pca.py
  scvid/module/onepass_mean_var_std.py
  scvid/module/probabilistic_pca.py
  scvid/module/tdigest.py
  scvid/train/training_plan.py
  setup.cfg
  setup.py
  test/test_dataset.py
  test/test_distributed_anndata.py
  test/test_ipca.py
  test/test_onepass_mean_var_std.py
  test/test_ppca.py
  test/test_sampler.py
  test/test_schema.py
  test/test_tdigest.py
  test/test_transforms.py
  versioneer.py
Labels: awaiting review, easy, refactor

#71 Create Documentation
  .github/workflows/docs.yml
  .gitignore
  docs/Makefile
  docs/make.bat
  docs/source/callbacks.rst
  docs/source/conf.py
  docs/source/data.rst
  docs/source/index.rst
  docs/source/module.rst
  docs/source/requirements.txt
  docs/source/trainer.rst
  docs/source/transforms.rst
  examples/incremental_pca.py
  examples/onepass_mean_var_std.py
  examples/probabilistic_pca.py
  examples/tdigest.py
  pyproject.toml
  scvid/callbacks/module_checkpoint.py
  scvid/data/__init__.py
  scvid/data/dadc_datamodule.py
  scvid/data/distributed_anndata.py
  scvid/data/read.py
  scvid/data/util.py
  scvid/module/probabilistic_pca.py
Labels: documentation, awaiting review

#73 `cellarium-ml`
  Makefile
  cellarium/__init__.py
  cellarium/ml/__init__.py
  cellarium/ml/callbacks/__init__.py
  cellarium/ml/callbacks/module_checkpoint.py
  cellarium/ml/callbacks/prediction_writer.py
  cellarium/ml/callbacks/variance_monitor.py
  cellarium/ml/data/__init__.py
  cellarium/ml/data/dadc_datamodule.py
  cellarium/ml/data/dadc_dataset.py
  cellarium/ml/data/distributed_anndata.py
  cellarium/ml/data/read.py
  cellarium/ml/data/sampler.py
  cellarium/ml/data/schema.py
  cellarium/ml/data/util.py
  cellarium/ml/module/__init__.py
  cellarium/ml/module/base_module.py
  cellarium/ml/module/from_cli.py
  cellarium/ml/module/gather.py
  cellarium/ml/module/incremental_pca.py
  cellarium/ml/module/onepass_mean_var_std.py
  cellarium/ml/module/probabilistic_pca.py
  cellarium/ml/module/tdigest.py
  cellarium/ml/train/__init__.py
  cellarium/ml/train/training_plan.py
  cellarium/ml/transforms/__init__.py
  cellarium/ml/transforms/transforms.py
  docs/source/callbacks.rst
  docs/source/data.rst
  docs/source/module.rst
  docs/source/trainer.rst
  docs/source/transforms.rst
  examples/README.rst
  examples/incremental_pca.py
  examples/onepass_mean_var_std.py
  examples/probabilistic_pca.py
  examples/tdigest.py
  test/test_dataset.py
  test/test_distributed_anndata.py
  test/test_examples.py
  test/test_ipca.py
  test/test_onepass_mean_var_std.py
  test/test_ppca.py
  test/test_read_h5ad.py
  test/test_sampler.py
  test/test_schema.py
  test/test_tdigest.py
  test/test_transforms.py
Labels: awaiting review

#75 Implement highly variable genes utils function
  cellarium/ml/utils/__init__.py
  cellarium/ml/utils/highly_variable_genes.py
  docs/source/index.rst
  docs/source/utils.rst
Labels: enhancement, awaiting review

#79 Deprecate single-consumer sampler non-iterable dataset classes
  cellarium/ml/data/__init__.py
  cellarium/ml/data/dadc_dataset.py
  cellarium/ml/data/sampler.py
  examples/incremental_pca.py
  examples/onepass_mean_var_std.py
  examples/probabilistic_pca.py
  examples/tdigest.py
  test/test_examples.py
  test/test_onepass_mean_var_std.py
  test/test_sampler.py
Labels: awaiting review, easy
