Repository cellarium-ai/cellarium-ml, pull requests merged in 2024-03, with the labels that each got.

#128 Update README.rst
  README.rst
Labels: documentation, awaiting review

#136 Use ruff formatter instead of black formatter
  Makefile
  README.rst
  cellarium/ml/cli.py
  cellarium/ml/models/geneformer.py
  notebooks/geneformer_demo.ipynb
  notebooks/mup_mlp.ipynb
  pyproject.toml
Labels: awaiting review, easy

#150 Refactor the negative binomial code
  cellarium/ml/core/module.py
  cellarium/ml/models/common/__init__.py
  cellarium/ml/models/common/distributions.py
  cellarium/ml/models/model.py
  cellarium/ml/models/scvi.py
  example_configs/scvi_config.yaml
  example_configs/scvi_pbmc_config.yaml
  notebooks/scvi_demo.ipynb
Labels: refactor

#155 Refactor common model code
  cellarium/ml/models/common/decoder.py
  cellarium/ml/models/common/encoder.py
  cellarium/ml/models/common/fclayer.py
  cellarium/ml/models/scvi.py
Labels: refactor
