Repository cellarium-ai/cellarium-ml, pull requests merged in 2024-04, with the labels that each got.

#156 scvi: make encoder/decoder more flexible
  cellarium/ml/models/common/fclayer.py
  cellarium/ml/models/common/nn.py
  cellarium/ml/models/model.py
  cellarium/ml/models/scvi.py
  example_configs/scvi_pbmc_config.yaml
Labels: enhancement, refactor

#154 Add shifted data algorithm for variance computation to `OnePassMeanVarStd`
  cellarium/ml/models/onepass_mean_var_std.py
  tests/test_onepass_mean_var_std.py
Labels: awaiting review

#165 Fix Geneformer docstring formatting
  cellarium/ml/models/geneformer.py
Labels: documentation, awaiting review

#172 Add `GatherLayer` test
  cellarium/ml/distributed/gather.py
  docs/source/distributed.rst
  docs/source/index.rst
  tests/distributed/test_gather.py
Labels: awaiting review

#164 Add short description and code organization section to README.rst
  README.rst
Labels: awaiting review

#173 Improve error messages
  cellarium/ml/cli.py
  cellarium/ml/data/dadc_dataset.py
  cellarium/ml/data/distributed_anndata.py
  cellarium/ml/data/fileio.py
  cellarium/ml/utilities/data.py
  tests/test_distributed_anndata.py
Labels: awaiting review

#169 scvi - enable batch embeddings, sampling, and freezing of batch bias computations
  cellarium/ml/models/common/nn.py
  cellarium/ml/models/scvi.py
  example_configs/scvi_pbmc_config.yaml
  notebooks/scvi_demo.ipynb
Labels: enhancement, refactor

#174 Fix README
  README.rst
Labels: awaiting review, easy
