Repository cellarium-ai/cellarium-ml, pull requests merged in 2025-02, with the labels that each got.

#298 Fix recent mypy errors
  cellarium/ml/layers/embedding.py
  cellarium/ml/layers/head.py
  cellarium/ml/models/onepass_mean_var_std.py
Labels: testing

#289 Fix the logic for merging odd number of devices in IncrementalPCA
  .github/workflows/ci.yml
  Makefile
  cellarium/ml/models/incremental_pca.py
  tests/test_ipca.py
  tests/test_onepass_mean_var_std.py
Labels: bug, awaiting review

#279 Cellarium gpt model
  cellarium/ml/layers/__init__.py
  cellarium/ml/layers/embedding.py
  cellarium/ml/layers/head.py
  cellarium/ml/layers/transformer.py
  cellarium/ml/models/__init__.py
  cellarium/ml/models/cellarium_gpt.py
  cellarium/ml/utilities/data.py
  cellarium/ml/utilities/mup.py
  tests/test_cellarium_gpt.py
Labels: awaiting review

#301 Add FSDP support
  cellarium/ml/callbacks/compute_norm.py
  cellarium/ml/core/module.py
  tests/test_callbacks.py
Labels: enhancement, awaiting review

#304 Add `CellariumModule.test_step` method for any custom inference
  cellarium/ml/core/datamodule.py
  cellarium/ml/core/module.py
  cellarium/ml/core/pipeline.py
  cellarium/ml/models/__init__.py
  cellarium/ml/models/model.py
Labels: enhancement, awaiting review
